version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # O la que uses tú (ej: 3.9)
    commands:
      - echo "[INSTALACIÓN] Instalando dependencias..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest pytest-mock
  pre_build:
    commands:
      - echo "[TEST] Ejecutando pruebas unitarias..."
      - PYTHONPATH=src pytest src/tests/ --junitxml=report.xml
  build:
    commands:
      - echo "[BUILD] Generando archivo ZIP para despliegue..."
      - zip -r app.zip * .[^.]*  # Empaqueta toda la app
artifacts:
  files:
    - app.zip
    - report.xml  # Opcional: para incluir reporte de pruebas
  discard-paths: yes
